import type { Game } from '../services/Cloud';

export function renderCertificate(container: HTMLElement, game: Game) {
  container.innerHTML = `
    <div class="certificate-view animate-fade-in" style="background: white; color: #1a1a1a; padding: 4rem; max-width: 850px; margin: 2rem auto; border: 15px solid #1a1a1a; position: relative;">
      <button id="close-cert" style="position: absolute; top: -50px; left: 0; background: transparent; border: 1px solid white; color: white;">← Back to Dashboard</button>
      <button id="print-cert" style="position: absolute; top: -50px; right: 0; background: var(--accent); color: white;">Print / Save as PDF</button>

      <div style="display: flex; justify-content: space-between; border-bottom: 2px solid #333; padding-bottom: 1rem; margin-bottom: 2rem;">
        <div>
          <h1 style="margin: 0; font-size: 2.5rem; letter-spacing: -2px;">OFFICIAL MATCH RECORD</h1>
          <p style="text-transform: uppercase; font-weight: bold; color: #666; font-size: 0.8rem; margin: 5px 0;">USA Water Polo | Verified Performance Data</p>
        </div>
        <div style="text-align: right;">
          <p style="margin: 0; font-weight: bold;">DATE: ${game.date}</p>
          <p style="margin: 0; font-size: 0.8rem; color: #666;">ID: ${game.id}</p>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 4rem; margin-bottom: 3rem;">
        <div style="padding: 1rem; border: 1px solid #ddd; border-radius: 4px;">
          <small style="color: #888;">HOME TEAM (SCANNED)</small>
          <h2 style="margin: 5px 0; font-size: 1.8rem;">VARSITY CLUB</h2>
          <div style="font-size: 3rem; font-weight: 800; margin-top: 10px;">${game.score.us}</div>
        </div>
        <div style="padding: 1rem; border: 1px solid #ddd; border-radius: 4px;">
          <small style="color: #888;">OPPONENT</small>
          <h2 style="margin: 5px 0; font-size: 1.8rem;">${game.opponent.toUpperCase()}</h2>
          <div style="font-size: 3rem; font-weight: 800; margin-top: 10px;">${game.score.them}</div>
        </div>
      </div>

      <h3 style="border-bottom: 1px solid #eee; padding-bottom: 0.5rem; margin-bottom: 1rem;">ROSTER STATISTICS</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 0.9rem;">
        <thead style="background: #f9f9f9;">
          <tr>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #333;">#</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #333;">PLAYER NAME</th>
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #333;">GOALS</th>
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #333;">FOULS</th>
          </tr>
        </thead>
        <tbody>
          ${game.stats.players.map((p: any) => `
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px;">${p.no}</td>
              <td style="padding: 10px; font-weight: bold;">${p.name}</td>
              <td style="padding: 10px; text-align: center;">${p.totalGoals}</td>
              <td style="padding: 10px; text-align: center;">${p.fouls.length}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div style="margin-top: 3rem; border-top: 2px solid #333; padding-top: 2rem;">
        <h3 style="margin-bottom: 1rem;">ORIGINAL SCORESHEET ARCHIVE</h3>
        <div style="background: #f0f0f0; border: 1px dashed #ccc; padding: 2rem; text-align: center;">
          <img src="${game.mediaUrl || ''}" style="max-width: 100%; border: 1px solid #ddd; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
          <p style="font-size: 0.7rem; color: #888; margin-top: 1rem;">Electronic verification signature: SHA256-${Math.random().toString(36).substr(2, 10)}</p>
        </div>
      </div>

      <div style="margin-top: 4rem; font-size: 0.7rem; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 1rem;">
        This document is an official digital record generated by WP Stat Tracker. 
        All data extracted and verified by AI-Vision.
      </div>
    </div>
  `;

  document.querySelector('#close-cert')?.addEventListener('click', () => {
    // Back to dashboard
    location.reload();
  });

  document.querySelector('#print-cert')?.addEventListener('click', () => {
    window.print();
  });

  // Scroll to top to see the certificate
  window.scrollTo(0, 0);

  // Custom print styles for the body to hide everything but the certificate
  const style = document.createElement('style');
  style.id = 'print-cert-style';
  style.innerHTML = `
    @media print {
      body * { visibility: hidden; }
      .certificate-view, .certificate-view * { visibility: visible; }
      .certificate-view { position: absolute; left: 0; top: 0; width: 100% !important; border: none !important; margin: 0 !important; padding: 0 !important; }
      #close-cert, #print-cert { display: none; }
    }
  `;
  document.head.appendChild(style);
}
